executor.py [LINE:362] #INFO     [2022-11-26 21:39:12,825] Bot: Evil Otter [@Evil_Otter_bot]
executor.py [LINE:358] #WARNING  [2022-11-26 21:39:12,949] Updates were skipped successfully.
dispatcher.py [LINE:358] #INFO     [2022-11-26 21:39:12,950] Start polling.
dispatcher.py [LINE:433] #INFO     [2022-11-26 21:39:22,897] Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 21:39:22,974] Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 21:39:25,024] Bot: Evil Otter [@Evil_Otter_bot]
executor.py [LINE:358] #WARNING  [2022-11-26 21:39:25,163] Updates were skipped successfully.
dispatcher.py [LINE:358] #INFO     [2022-11-26 21:39:25,164] Start polling.
base_events.py [LINE:1729] #ERROR    [2022-11-26 21:39:30,463] Task exception was never retrieved
future: <Task finished name='Task-14' coro=<Dispatcher._process_polling_updates() done, defined at C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\Foxy\PycharmProjects\Tbot\bot\main.py", line 76, in honda
    with open('parser/cards.json', 'r', encoding='UTF-8') as moto:
FileNotFoundError: [Errno 2] No such file or directory: 'parser/cards.json'
dispatcher.py [LINE:433] #INFO     [2022-11-26 21:39:36,891] Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 21:39:36,892] Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 21:40:24,765] Bot: Evil Otter [@Evil_Otter_bot]
executor.py [LINE:358] #WARNING  [2022-11-26 21:40:24,921] Updates were skipped successfully.
dispatcher.py [LINE:358] #INFO     [2022-11-26 21:40:24,921] Start polling.
dispatcher.py [LINE:433] #INFO     [2022-11-26 21:40:45,308] Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 21:40:45,309] Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 21:42:23,272] Bot: Evil Otter [@Evil_Otter_bot]
executor.py [LINE:358] #WARNING  [2022-11-26 21:42:23,400] Updates were skipped successfully.
dispatcher.py [LINE:358] #INFO     [2022-11-26 21:42:23,400] Start polling.
dispatcher.py [LINE:433] #INFO     [2022-11-26 21:42:35,347] Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 21:42:35,348] Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 21:42:39,352] Bot: Evil Otter [@Evil_Otter_bot]
executor.py [LINE:358] #WARNING  [2022-11-26 21:42:39,482] Updates were skipped successfully.
dispatcher.py [LINE:358] #INFO     [2022-11-26 21:42:39,483] Start polling.
dispatcher.py [LINE:433] #INFO     [2022-11-26 21:42:54,557] Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 21:42:54,558] Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 21:43:19,238] Bot: Evil Otter [@Evil_Otter_bot]
executor.py [LINE:358] #WARNING  [2022-11-26 21:43:19,385] Updates were skipped successfully.
dispatcher.py [LINE:358] #INFO     [2022-11-26 21:43:19,385] Start polling.
dispatcher.py [LINE:433] #INFO     [2022-11-26 21:43:23,229] Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 21:43:23,230] Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 21:43:25,052] Bot: Evil Otter [@Evil_Otter_bot]
executor.py [LINE:358] #WARNING  [2022-11-26 21:43:25,197] Updates were skipped successfully.
dispatcher.py [LINE:358] #INFO     [2022-11-26 21:43:25,197] Start polling.
base_events.py [LINE:1729] #ERROR    [2022-11-26 21:43:31,724] Task exception was never retrieved
future: <Task finished name='Task-26' coro=<Dispatcher._process_polling_updates() done, defined at C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\Foxy\PycharmProjects\Tbot\bot\main.py", line 60, in join
    d = sum(1 for line in open('user.txt'))
FileNotFoundError: [Errno 2] No such file or directory: 'user.txt'
base_events.py [LINE:1729] #ERROR    [2022-11-26 21:44:17,651] Task exception was never retrieved
future: <Task finished name='Task-35' coro=<Dispatcher._process_polling_updates() done, defined at C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\Foxy\PycharmProjects\Tbot\bot\main.py", line 60, in join
    d = sum(1 for line in open('user.txt'))
FileNotFoundError: [Errno 2] No such file or directory: 'user.txt'
base_events.py [LINE:1729] #ERROR    [2022-11-26 21:44:22,326] Task exception was never retrieved
future: <Task finished name='Task-42' coro=<Dispatcher._process_polling_updates() done, defined at C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\Foxy\PycharmProjects\Tbot\bot\main.py", line 60, in join
    d = sum(1 for line in open('user.txt'))
FileNotFoundError: [Errno 2] No such file or directory: 'user.txt'
dispatcher.py [LINE:433] #INFO     [2022-11-26 21:45:24,023] Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 21:45:24,023] Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 21:45:26,266] Bot: Evil Otter [@Evil_Otter_bot]
executor.py [LINE:358] #WARNING  [2022-11-26 21:45:26,424] Updates were skipped successfully.
dispatcher.py [LINE:358] #INFO     [2022-11-26 21:45:26,424] Start polling.
dispatcher.py [LINE:433] #INFO     [2022-11-26 21:45:40,737] Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 21:45:40,738] Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 21:49:54,995] Bot: Evil Otter [@Evil_Otter_bot]
executor.py [LINE:358] #WARNING  [2022-11-26 21:49:55,146] Updates were skipped successfully.
dispatcher.py [LINE:358] #INFO     [2022-11-26 21:49:55,147] Start polling.
dispatcher.py [LINE:433] #INFO     [2022-11-26 21:50:34,004] Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 21:50:34,005] Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 21:50:36,064] Bot: Evil Otter [@Evil_Otter_bot]
executor.py [LINE:358] #WARNING  [2022-11-26 21:50:36,194] Updates were skipped successfully.
dispatcher.py [LINE:358] #INFO     [2022-11-26 21:50:36,195] Start polling.
dispatcher.py [LINE:433] #INFO     [2022-11-26 21:50:38,621] Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 21:50:38,622] Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 21:50:40,647] Bot: Evil Otter [@Evil_Otter_bot]
executor.py [LINE:358] #WARNING  [2022-11-26 21:50:40,772] Updates were skipped successfully.
dispatcher.py [LINE:358] #INFO     [2022-11-26 21:50:40,773] Start polling.
dispatcher.py [LINE:433] #INFO     [2022-11-26 21:51:29,108] Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 21:51:29,109] Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 21:51:45,190] Bot: Evil Otter [@Evil_Otter_bot]
executor.py [LINE:358] #WARNING  [2022-11-26 21:51:45,321] Updates were skipped successfully.
dispatcher.py [LINE:358] #INFO     [2022-11-26 21:51:45,322] Start polling.
base_events.py [LINE:1729] #ERROR    [2022-11-26 21:52:12,244] Task exception was never retrieved
future: <Task finished name='Task-23' coro=<Dispatcher._process_polling_updates() done, defined at C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\Foxy\PycharmProjects\Tbot\bot\main.py", line 77, in honda
    with open('parser/cards.json', 'r', encoding='UTF-8') as moto:
FileNotFoundError: [Errno 2] No such file or directory: 'parser/cards.json'
base_events.py [LINE:1729] #ERROR    [2022-11-26 21:52:47,525] Task exception was never retrieved
future: <Task finished name='Task-32' coro=<Dispatcher._process_polling_updates() done, defined at C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "C:\Program Files\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\Foxy\PycharmProjects\Tbot\bot\main.py", line 77, in honda
    with open('parser/cards.json', 'r', encoding='UTF-8') as moto:
FileNotFoundError: [Errno 2] No such file or directory: 'parser/cards.json'
dispatcher.py [LINE:433] #INFO     [2022-11-26 21:52:50,924] Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 21:52:50,925] Goodbye!
